### ISSUE TITLE
git submodules can not found

### ISSUE THREAD

**Issue by UntaggedRui** [casys-kaist/LineFS#2]
It seems that some repos in .gitsubmodules can not found, such as` casys-kaist-internal/hyperloop.code.git` and `casys-kaist-internal/Pipeline-ioat-dma-kernel-module.git`.
So where can we find the submoule repos?

**Comment by yulistic** [comment]
Submodules are not necessary to run LineFS. Currently, we don't provide those submodules as open-source because they are minor features.

FYI, I resolved a dependency issue on `hyperloop` submodule (f4409f8572509e45101e4ca4cba55ec61ff01f49).
