### ISSUE TITLE
rdma_bind_addr failed

### ISSUE THREAD

**Issue by lyxxn0414** [casys-kaist/LineFS#3]
Hi, Kim, I'm trying to follow your work and met some problems when performing the step 9.3
### setup
I am trying to set up a cluster with 3 nodes.
and I got a segmentation fault
``` (core dumped) LD_LIBRARY_PATH=../${BUILD_REL}:../../libfs/lib/nvml/src/nondebug/ LD_PRELOAD=../../libfs/lib/jemalloc-4.5.0/lib/libjemalloc.so.2 $PINNING "$@"

After debugging with gdb, it seems the error is caused by rdma_bind_addr in line 71 file /usr/include/aarch64-linux-gnu/bits/string_fortified.h
I find that the cm_id is null and addr is 0.

Could you please help me with this problem? Thanks a lot!

**Comment by yulistic** [comment]
Which OS distribution are you using?

**Comment by lyxxn0414** [comment]
I use ubuntu18.04 for host and ubuntu20.04 for my snic. Thanks!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Apr 2, 2022 09:42 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [casys-kaist/LineFS] rdma_bind_addr failed (Issue #3)

&nbsp;



 
Which OS distribution are you using?

**Comment by yulistic** [comment]
And are you using NVIDIA Bluefield 1 DPU?

**Comment by lyxxn0414** [comment]
I'm using bf2.

--------------原始邮件--------------
发件人："Jongyul&nbsp;Kim ***@***.***&gt;;
发送时间：2022年4月5日(星期二) 下午2:38
收件人："casys-kaist/LineFS" ***@***.***&gt;;
抄送："李玥 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [casys-kaist/LineFS] rdma_bind_addr failed (Issue #3)
-----------------------------------

 

 
And are you using NVIDIA Bluefield 1 DPU?

**Comment by yulistic** [comment]
To run with BF2 card, I recommend updating `rdma-core` library at `libfs/lib/rdma-core` to the recent one. You can git clone from [here](https://github.com/linux-rdma/rdma-core).
You have to re-compile `libfs/lib/rdma` module and LineFS.

**Comment by lyxxn0414** [comment]
I have resolved this problem by updating rdma-core library. Thanks!
